name: CI

on: [push, pull_request]

jobs:
  mac:
    runs-on: macOS-latest
    env:
      CX_COMBINE_IMPLEMENTATION: CombineX
      CX_CONTINUOUS_INTEGRATION: "YES"
    steps:
      - uses: actions/checkout@v1
      - name: Swift Version
        run: swift --version
      - name: Build
        run: swift build

  # ios:
  #   runs-on: macOS-latest
  #   env:
  #     CX_COMBINE_IMPLEMENTATION: CombineX
  #     CX_CONTINUOUS_INTEGRATION: "YES"
  #   steps:
  #     - uses: actions/checkout@v1
  #     - name: Xcode Version
  #       run: xcodebuild -version
  #     - name: Build and Test
  #       run: |
  #         set -o pipefail
  #         xcodebuild build \
  #           -scheme MusicPlayer \
  #           -destination "platform=iOS Simulator,name=iPhone 12" | xcpretty

  linux:
    runs-on: ubuntu-latest
    container:
      image: swift:latest
    steps:
      - uses: actions/checkout@v1
      - name: Swift Version
        run: swift --version
      - name: Build
        run: swift build --product MusicPlayer

  combine:
    runs-on: macOS-latest
    env:
      CX_COMBINE_IMPLEMENTATION: Combine
      CX_CONTINUOUS_INTEGRATION: "YES"
    steps:
      - uses: actions/checkout@v1
      - name: Swift Version
        run: swift --version
      - name: Build
        run: swift build
